### PR TITLE
Gunslinger: Changed IDs and file location for v1.3

### PR DESCRIPTION
**Pull request by mol-tres**
Major Changes:
- Added separate Source (similar to `Bloodhunter (2020)`)
- Changed IDs and Sources of the elements
- Changed the file location to `third-party/dms-guild/classes/`

Minor Changes:
- Changed `<sheet>` to `<sheet display="false">` for the Subclass Archetype element
- Handful of small typos in `<sheet>` entries of some elements

### CODE REVIEW

**Comment by NickVendel** [comment]
it's not really 2020, though

**Comment by mol-tres** [comment]
I'm not sure, when v1.3 was released. The pdf is (c)2018, so I changed it to that.

**Comment by NickVendel** [comment]
I think it's good, but honestly, i think you're making pull request for wrong repo here, rather than trying to "fix experimental version", you could've just make a request in the main repository, then info box would make sense, otherwise it would just create issues. Experimental stuff is here for a reason, i don't plan to merge any content from here with main repository
\+ it's hard to tell if DMsGuild content even going to be added, there's uncertainty about that right now.

**Comment by NickVendel** [comment]
+ it's hard to tell if DMsGuild content even going to be added, there's uncertainty about that right now.

**Pull request closed without merging**
